
baseUrl: /demo
version: v1
apiUrl: ${baseUrl}/${version}
app:
  hikari: &hikari-common
    maximum-pool-size: '10'
    auto-commit: 'false'
    max-lifetime: '1800000'
    connection-timeout: '30000'
    minimum-idle: '1'
  datasource:
    maria:
      hikari: *hikari-common
      url: jdbc:mariadb://103.110.86.59:9000/employees?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC+7
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      username: employees
      password: employees
    clickhouse:
      hikari: *hikari-common
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://103.110.86.59:8123/examp
      username: floyd
      password: pink
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: 'true'
  main:
    allow-bean-definition-overriding: 'true'
jasypt:
  encryptor:
    password: 'amitiel'
info:
  build:
    description: '@project.description@'
    name: '@project.name@'
    version: '@build.version@'
    artifact: '@project.artifactId@'
management:
  server:
    port: 8080
    error:
      path: /error
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    db:
      enabled: false

